version = 1
SPDX-PackageName = "kpkpass"
SPDX-PackageSupplier = "Volker Krause <vkrause@kde.org>"
SPDX-PackageDownloadLocation = "https://invent.kde.org/pim/kpkpass"

[[annotations]]
path = [".gersemirc", "src/kpkpass-index.qdoc", "src/kpkpass.qdoc", "src/kpkpass.qdocconf"]
precedence = "aggregate"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"
